import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Proovider } from "./providers"; // (Note: Make sure 'Proovider' is spelled correctly in your file name too!)
import { AppbarClient } from "../app/components/AppbarClient";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ Everything is now safely inside the body tag */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Proovider>
          <AppbarClient />
          {children}
        </Proovider>
      </body>
    </html>
  );
}